spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.105:3306/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /Users/zhangmengmeng/Documents/CodeResource/SpringBoot/log
#  file: /Users/zhangmengmeng/Documents/CodeResource/SpringBoot/log/sell.log
##  level: debug
#  level:

#    com.zmm.sell.LoggerTest: debug